project_id = "aqromdreppgztagafinr"

[functions.create-user]
verify_jwt = true

[functions.transcribe-meeting]
verify_jwt = true

[functions.generate-ata]
verify_jwt = true

[functions.send-meeting-notification]
verify_jwt = true

[functions.send-meeting-reminders]
verify_jwt = false
